Ensure that organization label value is normalized in Azure CRs
giantswarm/azure-admission-controller pull request #49
Opened 2020-10-22 12:37 UTC by tuommaki

This change ensures that organization label value is normalized when new CR
objects are created for Azure clusters.

2020-10-22 13:26 UTC, tuommaki commented
Tested on `ghost` with an `AzureMachine` as well and this seems to work now.

2020-10-22 13:34 UTC, fiunchinho commented on pkg/generic/organization_label_normalizer.go
> +	// NOTE: Label key must be encoded as per RFC6901: https://tools.ietf.org/html/rfc6901#section-3
![](https://i.pinimg.com/originals/db/3a/31/db3a314fd9364c0354f3f2270647845c.gif)

2020-10-22 13:35 UTC, fiunchinho requested changes
Update the changelog please! otherwise LGTM

2020-10-23 08:21 UTC, axbarsan approved these changes

2020-10-23 08:57 UTC, fiunchinho approved these changes

2020-10-23 08:59 UTC, merged