Prevent Organization label change on UPDATE
giantswarm/azure-admission-controller pull request #51
Opened 2020-10-23 09:25 UTC by tuommaki

Once the cluster has been created in given organization, it can't be changed
anymore. Therefore it makes sense to prevent any updates to its value as well.

2020-10-23 10:12 UTC, fiunchinho commented on go.mod
> +	github.com/giantswarm/to v0.3.0
We are already depending on `autorest/to`. Let's use that instead of adding another dependency.

2020-10-23 10:15 UTC, fiunchinho requested changes
Your friend the Changelog needs an update :jack_o_lantern:

2020-10-26 07:14 UTC, tuommaki commented
> Your friend the Changelog needs an update

![Oops!](https://media.giphy.com/media/589QHtLROrpfi/giphy.gif)

2020-10-26 12:31 UTC, tuommaki commented
After the organization name normalization was removed. Do we need this? This is still valid restriction, but I'm not sure if this is strictly necessary?

2020-10-27 07:19 UTC, whites11 approved these changes
LGTM

2020-10-27 07:20 UTC, merged