Fix Cluster.Spec.ClusterNetwork.ServiceDomain validation and defaulting
giantswarm/azure-admission-controller pull request #95
Opened 2020-11-16 16:21 UTC by nprokopic

Here https://github.com/giantswarm/azure-operator/pull/1166 we fixed how we are setting `Cluster.Spec.ClusterNetwork.ServiceDomain` in azure-operator, this is to fix the validation and defaulting.

2020-11-16 16:25 UTC, fiunchinho requested changes
update the CHANGELOG please!

2020-11-16 16:27 UTC, nprokopic commented
> update the CHANGELOG please!

Damnit, I did it again :see_no_evil: Updated!

2020-11-16 16:35 UTC, fiunchinho commented on CHANGELOG.md
> +- Fix Cluster ServiceDomain validation and defaulting
```suggestion
- Default `Cluster.Spec.ClusterNetwork.ServiceDomain` to `cluster.local`.
- Make sure `Cluster.Spec.ClusterNetwork.ServiceDomain` is always `cluster.local`.
```

2020-11-16 16:35 UTC, fiunchinho approved these changes

2020-11-16 16:42 UTC, nprokopic commented on CHANGELOG.md
> +- Fix Cluster ServiceDomain validation and defaulting
Updated :)

2020-11-16 19:04 UTC, whites11 approved these changes
Looks good if fully tested

2020-11-17 04:59 UTC, tuommaki approved these changes

2020-11-17 08:30 UTC, tuommaki commented
I'll hijack here to unblock us. :slightly_smiling_face:

2020-11-17 08:31 UTC, merged